# 使用官方的 Python 基礎映像
FROM python:3.11

# 設置工作目錄
WORKDIR /app

# 複製當前目錄的內容到容器的工作目錄中
COPY . /app

# 安裝 Flask
RUN pip install flask

RUN pip install -r requirements.pip

# 暴露端口
EXPOSE 5443

# 設定容器啟動後運行的命令
CMD ["python", "app.py"]
