version: '3.6'

services:
  pdp_server:
    build: 
      context: ./pdp_server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always      
    volumes:
      - ./pdp_server:/app
      - ./pdp_server/node_modules:/app/node_modules
  
  fido2_server:
    build: 
      context: ./fido2_server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always
    environment:
      - FLASK_ENV=development      
    command: python app.py
    volumes:
      - ./fido2_server:/app
     