version: '3.6'

services:
  pdp_server:
    build: 
      context: ./pdp_server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always      
    volumes:
      - ./pdp_server:/app
      - ./pdp_server/node_modules:/app/node_modules
  
  fido2_server:
    build: 
      context: ./fido2_server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: always      
    volumes:
      - ./fido2_server:/app
      - ./fido2_server/node_modules:/app/node_modules