services:
  pep_web:
    build: 
      context: ./pep_web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - ./pep_web:/app
    restart: always

  pep_index:
    build:
      context: ./index
      dockerfile: dockerfile
    ports:
      - "50051:50051"
      - "2223:2223"
      - "3389:3389"
    volumes:
      - ./index:/app
    restart: always

  nginxproxyserver:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
 